version: v1.0
name: CI
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
jobs:
  build:
    name: Build and Test
    steps:
      - name: Checkout code
        commands:
          - checkout
      - name: Set up Python environment
        commands:
          - python -m venv venv
          - source venv/bin/activate
      - name: Install dependencies
        commands:
          - pip install -r requirements.txt
      - name: Run script
        commands:
          - python main.py
workflows:
  version: v1
  build_and_test:
    jobs:
      - build
blocks: []
