version: v1.0
name: CI
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
jobs:
  build:
    name: Build and Test
    steps:
      - name: Checkout code
        commands:
          - checkout
      - name: Set up Python environment
        commands:
          - python -m venv venv
          - source venv/bin/activate
      - name: Install dependencies
        commands:
          - pip install -r requirements.txt
      - name: Run script
        commands:
          - python main.py
workflows:
  version: v1
  build_and_test:
    jobs:
      - build
blocks:
  - name: 'Block #1'
    dependencies: []
    task:
      jobs:
        - name: 'Job #1'
          commands:
            - pip3.10 install -r requirements.txt
  - name: 'Block #2'
    dependencies:
      - 'Block #1'
    task:
      env_vars:
        - name: TELEGRAM_TOKEN
          value: '6953211957:AAE2rdKtITo6qVLjd_tF657pKz9-tj9EiNM'
      jobs:
        - name: 'Job #1'
          commands:
            - python3.10 main.py
  - name: 'Block #3'
    dependencies:
      - 'Block #2'
    task:
      jobs:
        - name: 'Job #1'
          commands: []
