version: v1.0
name: Telegram Song Downloader Bot
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
executor:
  name: 'python:3.9'
jobs:
  - name: Install dependencies
    commands:
      - pip install --upgrade pip
      - pip install python-telegram-bot spotdl python-dotenv
      - spotdl --download-ffmpeg
  - name: Run the bot
    commands:
      - python bot.py
pipeline:
  - name: Build and Run
    steps:
      - job: Install dependencies
      - job: Run the bot
blocks: []
