version: v1.0
name: Telegram Song Downloader Bot
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
executors:
  - name: 'python:3.9'
    docker:
      image: 'python:3.9'
jobs:
  - name: Install dependencies and run bot
    commands:
      - pip install --upgrade pip
      - pip install python-telegram-bot spotdl python-dotenv
      - spotdl --download-ffmpeg
      - python bot.py
pipeline:
  - name: Build and Run
    jobs:
      - Install dependencies and run bot
blocks: []
